### ISSUE TITLE
Copy controller into container instead of mounting

### ISSUE THREAD

**Issue by makandre** [appsody/appsody#467] opened 2019-10-17 14:13 UTC
**Is your feature request related to a problem? Please describe.**

In an upcoming release of Codewind, the existing `/codewind-workspace` docker bind mount will be removed.  This will mean that it's no longer possible to bind mount the controller located at `/codewind-workspace/.extensions/codewind-appsody-extension/bin/appsody-controller` into the Appsody container (since it won't exist anywhere on the host system anymore)

**Describe the solution you'd like**

Can we have an option to copy the controller into the Appsody container instead?

**Describe alternatives you've considered**

**Additional context**

**Comment by neeraj-laad** [comment] 2019-10-21 18:26
@chilanti is this duplicate of #399 ?

**Comment by chilanti** [comment] 2019-10-23 18:47
@neeraj-laad - closing as dup of #399, which articulates the problem (avoiding an extra bind mount or K8S volume mount) rather than indicating a solution.

**Closed by chilanti** 2019-10-23 18:47 UTC
Labels: codewind, design, enhancement
