### ISSUE TITLE
Support for local development with dependencies for appsody run

### ISSUE THREAD

**Issue by timroster** [appsody/appsody#197] opened 2019-08-17 23:36 UTC
**Is your feature request related to a problem? Please describe.**
When developing locally, it would be good to have an option for standing up dependencies as containers along with the appsody app. 

**Describe the solution you'd like**
Detect the presence of a docker compose file and use that with `appsody run` as an alternative to starting the application in a container. The option to specify the compose file to use (such as a -f option) may be preferable over simply autodetection of `docker-compose.yml`. This would allow the developer to stand up dependent containers (e.g. database) and provide credentials through env vars.

**Describe alternatives you've considered**
I'm currently doing this using `appsody build` to create the container and then running `docker-compose`.

**Additional context**
Some discussion about this feature from the Appsody slack: https://appsody.slack.com/archives/CKXDDB4A3/p1565968037043700

**Comment by neeraj-laad** [comment] 2019-08-20 12:33
This seems like a use case we would like to address but will need some more things and design discussions before we agree on the approach.

**Comment by timroster** [comment] 2019-08-25 12:59
With the addition/documentation of `--docker-options` and `--network` options to `appsody run`, it's easier to connect in dependencies when they are relatively simple. This is working much better than the alternative I previously mentioned.

**Comment by neeraj-laad** [comment] 2019-10-18 23:13
Closing this as a duplicate of #274 where we'll focus on achieving this for multiple environments, not just dev. 

Please feel free to re-open if you believe this will not be covered by that epic.

**Closed by neeraj-laad** 2019-10-18 23:13 UTC
