### ISSUE TITLE
Stack package command adds invalid image registry

### ISSUE THREAD

**Issue by haveroot** [appsody/appsody#804] opened 2019-12-12 09:15 UTC
**Describe the bug**
Packaging with image name space and omitted registry messes up the `.appsody-config.yaml` in the template `tar.gz`.

**To Reproduce**
1. `appsody stack package --image-namespace ns`
2. Go to the location where the templates zip stored e.g. `$HOME/.appsody/stacks/dev.local/somestack.tar.gz`
3. Unzip `somestack.tar.gz`and `cat .appsody-config.yaml`.
4. Following YAML is seen:

```yaml
stack: dev.local/ns/awesome-stack:0.0
```

**Expected behavior**
The `.appsody-config.yaml` should omit the registry name completely when `--image-registry` is not provided. But, this will probably be out of sync of listing seen in `docker images`. See below why omitting the registry name still makes sense.

**Actual behaviour**
Because the `.appsody-config.yaml` saves the `stack` with `dev.local` as the registry name, an `appsody init` starts looking for an image at `dev.local/ns/awesome-stack:0.0`; which won't exist.

**Work around**
Manually edit the `.appsody-config.yaml`, after initialisation, so that the stack points to the correct image registry.

**Environment Details (please complete the following information):**

```bash
appsody version
appsody 0.5.3
```

- OS : RHEL 7

```bash
uname -a
Linux myhost 3.10.0-1062.4.3.el7.x86_64 #1 SMP Tue Nov 12 10:42:40 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by neeraj-laad** [comment] 2019-12-12 13:23
The change was made to keep the behaviour of appsody stack package consistent and predictable. With various flags, the value can be overridden or the default value is used. This will result in each appsody_config.yaml having a fully qualified image reference to the stack image.

Image registry - defaults to dev.local to keep it separate from final images for publishing
Image namespace - defaults  to appsody

With this in mind, I see stack developers trying `appsody stack package` to get local stack and `appsody stack package --image-registry <reg> --image-namespace <ns>` for final publishing.

**Comment by kylegc** [comment] 2019-12-12 18:47
To add a few more points, by default, we don't want a user's custom stack to conflict or overwrite an existing stack/image on docker.io. For example, you may be developing/testing a new version of a stack that already exists on docker.io.
Thus the registry `dev.local` is added to clearly state this is a development stack and it is staying local to you. It avoids unpredictable behavior and accidentally pushing it to docker.io. 

@haveroot I don't agree with your work around. You shouldn't manually edit the `.appsody-config.yaml`, the fully qualified stack (e.g. `dev.local/ns/awesome-stack:0.0`) will work just fine on your local machine.

Typically the publishing/pushing of a production stack will happen in a build pipeline. There, the pipeline can be set up to specify the correct `--image-registry` and `--image-namespace`

**Comment by chainhead** [comment] 2019-12-14 04:43
> I don't agree with your work around. You shouldn't manually edit the .appsody-config.yaml, the fully qualified stack (e.g. dev.local/ns/awesome-stack:0.0) will work just fine on your local machine.

That is true only if there is a cached image `dev.local/ns/awesome-stack:0.0` on that local machine, right? Or, are you saying, it will also work on stack consumer's local machine also - even if the custom stack wasn't ever initialised before?

**Comment by ebullient** [comment] 2019-12-16 14:49
A stack consumer would expect to pull from a published/reachable registry, which means their `appsody init` would work against a publicly available image (post-publish of stack and supporting resources).

A stack maintainer using `dev.local` is a one-off that is unique to stack development.

**Comment by neeraj-laad** [comment] 2020-01-09 12:22
I believe this is working as designed and I hope the discussion above would have helped in understanding the reasons for implementing it that way. 

Closing this issue, please re-open if the issue if you want to discuss this further or suggest a different way that improves on current implementation.

**Closed by neeraj-laad** 2020-01-09 12:22 UTC
