### ISSUE TITLE
Sporadically, `appsody deploy` fails to display the URL of the Knative service

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#84] opened 2019-07-17 22:15 UTC
**Describe the bug**
At times, `appsody deploy` fails to print out the URL of the Knative service. This happens in spite of the fact that the service was deployed successfully

**To Reproduce**
1. Create an appsody project with `appsody init <your stack>`
2. Deploy it on K8S (`appsody deploy`)
3. Occasionally - but not always - you'll see a message that says that the URL of the Knative service could not be retrieved, even though the service was successfully deployed.

**Expected behavior**
The problem occurs - very likely - because of the asynchronous nature of `kubectl apply` - which completes its execution before all the resources that are created are made available.  Two possible behaviors would be desirable:
1) Produce a better message, that clarifies that the URL is not yet available, and show the `kubectl` command that the user can run to retrieve it at a later time.
2) Catch the error, wait, retry a few times.

**Actual behaviour**
An error is displayed - even though this may be a timing issue.

**Environment Details (please complete the following information):**
 - OS: all
 - Browser N/A

**If applicable please specify:**
 - CLI version: 0.2.5
 - Stack you are using: Not relevant

**Screenshots**

**Additional context**

**Comment by seabaylea** [comment] 2019-07-19 12:02
I suspect that this is a timing issue - that occasionally the kubectl query occurs before the route/dns name field is set up.

**Comment by neeraj-laad** [comment] 2019-09-18 13:53
We are not able to reproduce this any more. Closing for now. Will re-open if needed

**Closed by neeraj-laad** 2019-09-18 13:53 UTC
Labels: bug
