### ISSUE TITLE
Appsody run doesn't properly terminate the process

### ISSUE THREAD

**Issue by sdaschner** [appsody/appsody#118] opened 2019-07-26 11:17 UTC
**Describe the bug**
It seems that stopping `appsody run` (and others) doesn't properly terminate the underlying process. I haven't looked into what happened under the hood just yet, however the output of, for example, the Maven process in `java-microprofile` doesn't print the usual stopping that it does when hitting `Ctrl + C` in the command line, and neither does `appsody run` wait for the embedded server to stop.

If the process (e.g. the running server) is just being killed without having received a `TERM` signal then resources and connections as not properly closed and released.

**To Reproduce**
1. Run `appsody run` in a `java-microprofile` project and hit `Ctrl + C`
2. The process just stops and doesn't seem to shutdown the server.
3. Compare with running the `mvn` command locally and hit `Ctrl + C`

**Expected behavior**
Stopping whatever is running with a proper `TERM` signal. This might require proper handling of Unix signals to potential child processes.

**If applicable please specify:**
 - CLI version: `appsody 0.2.5`
 - Stack you are using: `java-microprofile` and home-grown stacks

**Additional context**
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by neeraj-laad** [comment] 2019-07-29 09:11
@cappsody/cli

**Comment by neeraj-laad** [comment] 2019-10-18 22:20
@sdaschner I'm curious to understand if you have seen any specific resources/connections not being released on the host machine?  

@kewegner what do we use in cli / controller to terminate a running process?

Could this be related to the issue where users can not start the appsody local dev container because a port is not available, but they can't see the port in use anywhere else.

**Comment by sdaschner** [comment] 2019-10-19 07:16
@neeraj-laad Yes, especially network connections that then run into timeouts. In general, it's a rather bad practice to just kill a process and not terminate it properly and giving a chance to clean up.

What needs to be done is that the controller keeps a reference to all process IDs it starts and send TERM signals to them on process termination (e.g. by using quit traps in shell scripts).

**Comment by kewegner** [comment] 2019-10-21 12:18
So there are two cases.  When we detect on change events we do send SIG TERMS to the processes the controller starts.  (both to the process for APPSODY RUN and the ON_CHANGE processes.

The subprocesses are part of the same process group as the controller.

In the case of appsody stop or control c, a docker stop is performed which sends a sig term to the controller, since the other processes are child processes of the controller.

In theory if applications are part of the same process group, all child applications are suppose to receive a sig term.

Currently the controller does not have its own signal handler which could do the equivalent handling of sd's example.  The other issue is whether there is adequate time for each child process to handle the sig term.

**Comment by kewegner** [comment] 2019-10-22 20:57
@neeraj-laad I am working on a fix for this issue.  Do we have access to a stack with either the liberty:dev .bak file spoken of or the issue with the ports you spoke of (or are they the same issue).

**Comment by kewegner** [comment] 2019-10-23 14:03
@gcharters is there a sequence of steps to reproduce the issue with liberty dev and the .bak file you reference?  I would like to test the code change I'm making with that use case.  Neeraj is going to point me to a liberty dev project I can try liberty dev with (for the issue he raised).

**Comment by gcharters** [comment] 2019-10-24 16:01
@kewegner the sequence it to repeatedly start with `appsody run` and stop with `ctrl-C`.  Unfortunately, it did not happen every time, but did occur reasonably frequently.

**Comment by kewegner** [comment] 2019-10-24 21:29
I reproduced the error on 0.4.7 of Appsody CLI for libery dev.  I did not see the error the times I was able to test with the new signal handler, but more test is required

**Closed** 2019-11-14 17:01 UTC
Labels: bug
