### ISSUE TITLE
Appsody on K8S should avoid separate mount for the controller

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#399] opened 2019-10-04 18:51 UTC
**Is your feature request related to a problem? Please describe.**
Appsody on K8S should minimize the number of volume mounts. Currently, it requires a separate PVC for the appsody controller, which could be copied in the workspace mount.

**Describe the solution you'd like**
Remove the PVC for controller, and copy the appsody controller into the workspace instead. The deployment yaml that gets generated by `appsody run` needs to reflect the new mount strategy.

**Describe alternatives you've considered**
Leave things as they are today and have Che only use a single volume for all users where the controller is stored.

**Comment by neeraj-laad** [comment] 2019-10-21 18:27
Duplicate of #467

**Comment by chilanti** [comment] 2019-10-23 18:53
This issue should address both the "local" use cases (with or without Codewind) - and the K8S use cases. In essence, we want to avoid bind mounting the controller (local case), and using a shared volume mount for K8S. 

The current thinking is to have the CLI create a docker volume in the local use case, and to pre-populate the docker volume with the controller. Then, `appsody run` would instruct the stack container to volume mount the volume (i.e. no more loading the controller from the Appsody CLI file system). 
Similarly, in the K8S case, an init container would populate a K8S `emptyDir` volume with the controller, and the stack container would mount the same volume, eliminating the need for shared volumes across the CLI pod and the stack pod. 

The approach is illustrated in the attachment.
[Controller mount.pptx](https://github.com/appsody/appsody/files/3763969/Controller.mount.pptx)

**Closed** 2019-11-12 17:07 UTC
Labels: codewind, design, enhancement
