### ISSUE TITLE
appsody run ctrl c gives sleeping 60 seconds message 

### ISSUE THREAD

**Issue by tnixa** [appsody/appsody#344] opened 2019-09-18 20:04 UTC
**Describe the bug**
When i do an appsody run and kill is using ctrl c I get a message
`[Container] ^CClosing down development environment, sleeping 60 seconds: exit status 2`
which makes me thing it is sleeping for 60 seconds but it returns within a couple seconds. This message did not happen with the previous release in this scenario. If I do `appsody run -i`  and kill it with ctrl c I get the same message but it actually does a 60 second sleep before returning.

I'm also not sure what `exit status 2` is supposed to mean. I think I was getting `exit status 1` with the previous CLI release

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**If applicable please specify:**
 - CLI version: 0.4.4 plus fixes
 - Stack you are using: nodejs

**Comment by henrynash** [comment] 2019-09-18 20:11
I did already raise an issue for this https://github.com/appsody/appsody/issues/334 
(although you have added some extra info)

**Comment by kylegc** [comment] 2019-09-19 13:23
Closing as duplicate of #334

**Closed by kylegc** 2019-09-19 13:23 UTC
Labels: duplicate
