### ISSUE TITLE
Java apps cannot detect whether console is interactive TTY

### ISSUE THREAD

**Issue by ericglau** [appsody/appsody#670] opened 2019-11-19 21:58 UTC
**Describe the bug**
Java apps cannot detect whether the console is interactive TTY.  If a stack runs a Java app that expects interactive TTY, it needs to be able to detect whether it is actually interactive or not, and react appropriately.

**To Reproduce**
1. Package this stack and initialize it: https://github.com/ericglau/interactive-stack , which has just a basic [Java class](https://github.com/ericglau/interactive-stack/blob/master/templates/hello/src/main/java/com/sample/App.java) that tries to read system input.
2. Run as interactive mode: `appsody run --interactive`
3. Wait until you see: `Waiting for input...`
4. Then press Enter, which causes the following to be printed: `Line detected`, then it quits.
5. Run as non-interactive mode: `appsody run`
6. Wait until you see: `Waiting for input...`
7. Try pressing Enter, and nothing happens.  It is stuck waiting for input because Appsody is not in interactive mode, and the application has no way to detect this.

**Expected behavior**
The application should detect that there is no input on System.in, and therefore `Scanner.hasNextLine()` should be able to return immediately with `false`.  

Alternatively, use the [console](https://github.com/ericglau/interactive-stack/blob/console/templates/hello/src/main/java/com/sample/App.java) branch of the above stack which uses `System.console()` instead of `Scanner`. `System.console().readLine()` should return immediately if there is no input available.

**Actual behaviour**
`Scanner.hasNextLine()` or `System.console().readLine()` hangs waiting for input.

**Environment Details (please complete the following information):**
 - macOS 10.15.1

**If applicable please specify:**
 - CLI version: Appsody 0.5.0, but the problem also occurs with 0.4.4 and 0.4.5.
 - Stack you are using: https://github.com/ericglau/interactive-stack

**Additional context**
I tried the same `Scanner.hasNextLine()` logic before `--interactive` was implemented, and it was able to return immediately with `false`.  Unfortunately I do not have records of what Appsody version I used with that, and cannot find any Appsody binaries lower than 0.4.4 on the releases page.

**Comment by kylegc** [comment] 2019-11-19 22:22
Thanks Eric, we'll take a look.

@kewegner this is probably because the controller is running interactive. Can you take a look?

**Comment by kewegner** [comment] 2019-11-19 22:56
I reproduced, but what was odd when I ran it initially it worked, then I reinstalled appsody and it started failing.  We'll investigate.

**Comment by kewegner** [comment] 2019-11-20 14:38
Update it is setting the cmd.Stdin that causes the issue.

**Comment by kewegner** [comment] 2019-11-20 22:38
This PR will have to be merged into appsody/controller and we'll need a new release of controller prior to putting in the CLI side of this fix.

https://github.com/appsody/controller/pull/54

**Closed** 2019-12-02 22:19 UTC
Labels: bug
