### ISSUE TITLE
Enhance the CLI build process to create Homebrew bottles for macOS

### ISSUE THREAD

**Issue by chilanti** [appsody/appsody#39] opened 2019-07-01 18:30 UTC
Currently, the Homebrew installer forces a build from source (even though we are not packaging any source in the installer). The build process should generate bottles for Mojave, and High Sierra (at least).

**Comment by neeraj-laad** [comment] 2019-07-18 09:18
@chilanti Is there still some outstanding work on this issue?

**Comment by chilanti** [comment] 2019-07-23 03:03
We should postpone this issue. It won't be possible to have bottles until we can create a pull request against the main homebrew repo.

**Comment by neeraj-laad** [comment] 2019-10-14 14:18
Closing this as a duplicate of #417

**Closed by neeraj-laad** 2019-10-14 14:18 UTC
