### ISSUE TITLE
Add default executable field to `.appsody-config.yaml`

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/appsody#415] opened 2019-10-08 14:24 UTC
**Is your feature request related to a problem? Please describe.**
In the case where multiple executables exists within a project, the `appsody run` command does not know which one to execute. This is the case for the`swift` stack when using the slim docker images as discussed with @ianpartridge, and in the `rust` stack being developed by @skoh7645.

**Describe the solution you'd like**
Enable the user to specify a default executable within the `.appsody-config.yaml` file which gets called at `appsody run`.

**Describe alternatives you've considered**
An alternative would be to pass a flag to the specific language such as `--executable-name <name>`. In Rust, it would get passed to `cargo build --bin <name>`.

**Additional context**
Currently, we default to executing the release version.

**Comment by seabaylea** [comment] 2019-10-08 16:35
In the specific case for Swift, we could resolve this by pulling the name of the built binary from the end of the build log and passing that (via a script) into the "slim" image to run the binary.

That doesn't negate the value in being able to manually specify the executable, but it we can do it automatically for Rust, we should do that as well..

**Comment by seabaylea** [comment] 2019-10-08 16:36
Here's where we do that in case it's useful:
https://github.com/appsody/stacks/blob/master/incubator/swift/image/project/Dockerfile#L13

**Comment by EnriqueL8** [comment] 2019-10-09 10:41
Cargo does not provide the executable path normally when running `cargo build`, so initially we were running `cargo run` to get it, but this is the wrong behavior for `appsody build`. We have found that when building in verbose: `cargo build --verbose`, it calls the rust compiler specifying the `crate name` and the folder where the executable will be place. We can then extract this the same way Swift does it, and pass it to a script.

In the case where multiple executables exists, we will need to default to one meaning that the user will not be able to specify an executable. We can document this as a limitation for the meantime.

**Comment by kylegc** [comment] 2019-10-09 19:38
@EnriqueL8 this issue's initial description states the problem is with `appsody run`, however the rest of the discussion (including appsody/stacks#125) revolves around `appsody build` and the "slim" production image. So I'm trying to understand if the problem really applies to both appsody run and build, or just build?

**Comment by EnriqueL8** [comment] 2019-10-10 09:08
The problem is around locating the executable of the project in order to call it when running `appsody run`. When running `appsody build`, the compiler is creating the executable for the project. At that point in time, we have to store the location, and pass it to the `CMD` in the Dockerfile which gets executed at `appsody run`. 

This is done in the swift stack as Chris mentioned, by pulling the name of the binary from the `swift build` command (link he provide), feeding it into a script , and calling that script at https://github.com/appsody/stacks/blob/master/incubator/swift/image/project/Dockerfile#L32.
In Rust, the `cargo build -v` command as @skoh7645  found output a sanitized binary name which can be different from the actual binary. Currently in Rust, we will find the binary in the project, and run the one in the release folder. Then document as a limitation. Maybe this use case explains it a bit better: https://thefullsnack.com/en/multiple-binaries-rust.html

**Comment by kylegc** [comment] 2019-10-10 13:31
@EnriqueL8 I still don't understand the `appsody run` scenario. `appsody run` is used in development mode to execute your latest code and iterate on code changes before `appsody build/deploy` is run. It doe not use `CMD` or the `Dockerfile` at all, it uses the `APPSODY_RUN` environment variable of the stack image ( in the `Dockerfile-stack`).

**Comment by EnriqueL8** [comment] 2019-10-10 13:38
Yes, sorry I confused `appsody run` with `docker run`. So this scenario within appsody would be when running `appsody deploy`.

**Comment by kylegc** [comment] 2019-10-10 14:41
Thanks for the clarification, that makes more sense. Please update the issue description to say `docker run`.

I think this is a duplicate of appsody/stacks#125 @EnriqueL8 do you agree? If so, let's merge the information from the two issues into one and start discussing implementation options there.

**Comment by neeraj-laad** [comment] 2019-10-16 13:53
Closing as dupl}}}}}}}}}}||




||||||||~

**Closed by neeraj-laad** 2019-10-16 13:53 UTC
