### ISSUE TITLE
Allow templates to be fetched from inside the image

### ISSUE THREAD

**Issue by ebullient** [appsody/appsody#188] opened 2019-08-15 19:33 UTC
See appsody/stacks#181

Is your feature request related to a problem? Please describe.

As stacks are customized and distributed, it becomes increasingly likely that templates and stacks will get out of sync (since they are published as separate artifacts). Templates are comparatively thin, but often depend on the build behavior of the stack (at least in a "this template requires this minimum version of the stack" sense).

Describe the solution you'd like

I think the templates should be packaged inside the stack. That way, you can extract/use a template from any stack image, and you never get into the situation where a project can't be created because the two separate publishing mechanisms are out of sync.

From an index.yaml POV, this could look something like this:

  - id: java-spring-boot2
    name: Spring Boot®
    version: 0.4.0
    description: Spring Boot using OpenJ9 and Maven
    license: Apache-2.0
    maintainers:
      - name: Erin Schnabel
        email: schnabel@us.ibm.com
        github-id: ebullient
    default-template: default
    templates:
      - id: default
        url: image:/templates/default.tgz
      - id: kotlin
        url: image:/templates/kotlin.tgz
    image: appsody/java-spring-boot2:0.4.0

If the image: URL is present, then the image tag is used to find the templates (this assumes one image per appsody stack).

**Comment by smcclem** [comment] 2019-09-19 17:25
+1 . I am not exactly sure what all @ebullient had in mind, but I would want to see it where you could init a project directly from the docker image, rather than a repo.  Something like:

appsody init -i  appsody/nodejs-express:0.2

**Comment by henrynash** [comment] 2019-09-19 19:03
@smcclem absolutely 100% agree! That's what I really have in mind as a consequence of https://github.com/appsody/stacks/issues/324

**Comment by ebullient** [comment] 2019-10-04 15:31
The new `appsody stack package` command conflicts with this, as it seems to throw an error if the template directory is not present. In the existing package script, I can compensate for a missing template directory (extracting templates from the image instead). The `stack package` command has effectively made this impossible without a code change in the CLI

**Comment by kylegc** [comment] 2019-10-04 16:35
Quite a bit of changes would be needed in the CLI (not just the new `stack package` command)  if/when we adopt this proposal. 
@ebullient are you blocked or can you just continue to use the previous scripts for now?

**Comment by neeraj-laad** [comment] 2019-10-18 23:06
This will be a big change and impact lots of places. Let's discuss and refine the idea of using https://github.com/appsody/stacks/issues/324 as it primarily deals with how a stack and it's components are delivered.

Closing this issue for now. as a duplicate of that one. We can re-open issues on each component impacted once we have a clear and agreed approach on this.

**Closed by neeraj-laad** 2019-10-18 23:06 UTC
